// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1_AspNetCoreWebApp_VC.Data;

namespace WebApplication1_AspNetCoreWebApp_VC.Migrations
{
    [DbContext(typeof(WebApplication1_AspNetCoreWebApp_VCContext))]
    partial class WebApplication1_AspNetCoreWebApp_VCContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClassLibrary1_Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bebidas ....",
                            Name = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comidas ....",
                            Name = "Comida"
                        });
                });

            modelBuilder.Entity("ClassLibrary1_Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateRegist")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<bool>("Stock")
                        .HasColumnType("bit");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegist = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Agua Frize ....",
                            Name = "Agua Frize",
                            Price = 0.0,
                            Stock = false,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 2,
                            DateRegist = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sumol Ananas ....",
                            Name = "Sumol",
                            Price = 0.0,
                            Stock = false,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateRegist = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bifes... ....",
                            Name = "Bifes",
                            Price = 0.0,
                            Stock = false,
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = 4,
                            DateRegist = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Costelas... ....",
                            Name = "Costelas",
                            Price = 0.0,
                            Stock = false,
                            SubCategoryId = 4
                        });
                });

            modelBuilder.Entity("ClassLibrary1_Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Refrigentes ....",
                            Name = "Refrigentes"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Aguas ....",
                            Name = "Aguas"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Porco ....",
                            Name = "Porco"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Frango ....",
                            Name = "Frango"
                        });
                });

            modelBuilder.Entity("ClassLibrary1_Models.Product", b =>
                {
                    b.HasOne("ClassLibrary1_Models.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ClassLibrary1_Models.SubCategory", b =>
                {
                    b.HasOne("ClassLibrary1_Models.Category", "Category")
                        .WithMany("SubCategorys")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ClassLibrary1_Models.Category", b =>
                {
                    b.Navigation("SubCategorys");
                });

            modelBuilder.Entity("ClassLibrary1_Models.SubCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
